### ISSUE TITLE
Dont transition to awaiting changes for simple comments

### ISSUE THREAD

**Issue by blaggacao** [timokau/marvin-mk2#56] opened 2020-07-07 19:51 UTC
https://github.com/NixOS/nixpkgs/pull/78451#issuecomment-655088862

(I think #49 would avoid this, by acting upon github "unresolved reviews")

**Comment by timokau** [comment] 2020-07-07 20:07
This is a duplicate of / has overlap with #44. I'll close this one and take this as extra context. I agree that the more drastic version suggested in #44 and here (only transition on actual change-requesting reviews) is probably the way to go, since we want to avoid transitioning into the "sink-state" on accident.

**Comment by timokau** [comment] 2020-07-07 20:09
Thanks for the feedback, the actual interaction you linked is helpful :)

**Closed by timokau** 2020-07-07 20:09 UTC

**Comment by timokau** [comment] 2020-07-07 21:37
Fixed in #58.
